
# Windows Build Configuration for AppVeyor
# http://www.appveyor.com/docs/appveyor-yml

# build version format
version: "{build}"

os: Visual Studio 2019

platform:
  - x64

configuration:
  - Release

branches:
  only:
    - master

build:
  parallel: true
  verbosity: minimal

build_script:
  - git checkout tests
  - git submodule update --init --recursive
  - mkdir visualstudio && cd visualstudio
  - cmake .. -DXWIN_TESTS=ON
  - cmake --build .
  - ctest . -C Debug --verbose

test_script:

notifications:
  - provider: Email
    to:
      - '{{commitAuthorEmail}}'
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false